before_script:
  - apt-get update -qq && apt-get install -y cmake gcc g++

build:
    script:
        - export dir=$(pwd)
        - mkdir build install
        - cd build
        - export BUILD_TYPE=RELEASE
        - cmake .. -DWRP_ROOT=$dir -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=$BUILD_TYPE
