stages:
  - build
  - test

build:linux:rel:
    stage: build
    script:
        - apt-get update -qq && apt-get install -y cmake gcc g++ git
        - export dir=$(pwd)
        - git submodule update --init --recursive
        - mkdir build install
        - cd build
        - export BUILD_TYPE=Release
        - cmake .. -DWRP_ROOT=../ -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        - cmake --build . --config $BUILD_TYPE --target install
        - ./build/bin/unit_tests
test:
    stage: test
    script:
        - ls -lai
        - ./build/bin/unit_tests

