before_script:
  - apt-get update -qq && apt-get install -y cmake gcc g++

build:
    script:
        - cd wrp/
        - ./run/build.sh . Release
.test:default:
  script:
    - ./build/bin/unit_tests
