before_script:
  - apt-get update -qq && apt-get install -y cmake gcc g++

build:
    script:
        - dir=$(pwd)
        - ./run/build.sh $dir Release
test:
  script:
    - cd $dir
    - ./build/bin/unit_tests
