stages:
  - build
  - test

build:linux:rel:
    stage: build
    script:
        - apt-get update -qq && apt-get install -y cmake gcc g++
        - export dir=$(pwd)
        - mkdir build install
        - cd build
        - export BUILD_TYPE=RELEASE
        - cmake .. -DWRP_ROOT=$dir -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=$BUILD_TYPE

run-unit-test:
    stage: test
    script:
        - echo $dir
        - ./build/bin/unit_tests

