stages:
  - build
  - test

before_script:
  - apt-get update -qq && apt-get install -y cmake gcc g++ lcov

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

build:linux:rel:
    stage: build
    script:
        - export dir=$(pwd)
        - mkdir build install
        - cd build
        - export BUILD_TYPE=Release
        - cmake .. -DWRP_ROOT=$dir -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        - cmake --build . --config $BUILD_TYPE --target install
        - ./bin/unit_tests
        - lcov --capture --directory . --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
        - lcov --list coverage.info # debug info
    # artifacts:
    #   name: "$(eval echo $BUILD_TYPE)"
    #   expire_in: 1 hour
    #   when: always
    #   paths:
    #     - "$CI_PROJECT_DIR/output.txt"

build:linux:deb:
    stage: build
    script:
        - export dir=$(pwd)
        - mkdir build install
        - cd build
        - export BUILD_TYPE=Debug
        - cmake .. -DWRP_ROOT=$dir -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        - cmake --build . --config $BUILD_TYPE --target install
        - ./bin/unit_tests
        - lcov --capture --directory . --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
        - lcov --list coverage.info # debug info
    # artifacts:
    #   name: "$(eval echo $BUILD_TYPE)"
    #   expire_in: 1 hour
    #   when: always
    #   paths:
    #     - "$CI_PROJECT_DIR/output.txt"

